server:
  port: 8081
  tomcat:
    threads:
      max: 1000
      min-spare: 500
    accept-count: 5000

spring.threads.virtual.enabled: true


management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: info, health, metrics, prometheus
  #        include: "*"
  metrics:
    tags:
      application: api-monitor